name: deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://ich-heisse.marvin.pro
    steps:
      - uses: actions/checkout@v2
      - name: setup google cloud sdk
        uses: google-github-actions/setup-gcloud@v0.5.1
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_KEY }}
          export_default_credentials: true
      - name: deploy to gcs
        run: gsutil -m rsync -r -d ./public gs://ich-heisse.marvin.pro
